FROM mcr.microsoft.com/devcontainers/base:bullseye

COPY ./docker_setup_common.sh ./setup.sh

# Make the script executable
RUN chmod +x ./setup.sh

# Default command to run the script
CMD ["./setup.sh"]


ARG IS_VSCODE=true
RUN if [ "$IS_VSCODE" = "false" ]; then exit 0; fi

ARG USERNAME=vscode

# Used to persist bash history as per https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R $USERNAME /commandhistory \
    && echo "$SNIPPET" >> "/home/$USERNAME/.bashrc"
