FROM mcr.microsoft.com/devcontainers/base:bullseye

COPY ./docker_setup_common.sh ./setup.sh

# Make the script executable
RUN chmod +x ./setup.sh

# Default command to run the script
CMD ["./setup.sh"]

# Create a new user
RUN useradd agent

# Switch to the new user
USER agent
