name: 'Docker Build and Push Action'
description: 'Builds and pushes a Docker image'
inputs:
  docker-image-tag:
    description: 'Docker image tag'
    required: true
  docker-file-path:
    description: 'Path to the target docker file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ inputs.docker-file-path }}
        push: true
        tags: ${{ vars.DOCKER_IMAGE_REPO }}:${{ inputs.docker-image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max