name: 'Docker Build and Push Action'
description: 'Builds and pushes a Docker image'
inputs:
  image-tag:
    description: 'Docker image tag'
    required: true
  file-path:
    description: 'Path to the target docker file'
    required: true
  repo:
    required: true
  username:
    required: true
  auth-token:
    required: true
outputs:
  published-image:
    description: 'the repo:tag of the published image'
runs:
  using: 'composite'
  steps:
    - name: Get branch name
      id: get_git_branch
      run: |
        echo "branch=${GITHUB_REF#refs/heads/}" 
        echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      shell: bash

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.auth-token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ inputs.docker-file-path }}
        push: true
        tags: ${{ inputs.repo }}:${{ inputs.docker-image-tag }}-${{ steps.get_git_branch.outputs.branch }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image tag
      run : |
        echo "::set-output name=published-image::$(echo ${{ inputs.repo }}:${{ inputs.docker-image-tag }}-${{ steps.get_git_branch.outputs.branch }})"