name : 'Get Git Branch'
description : 'Retrieves git branch name'
outputs:
  branch:
    description: 'The name of the branch'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get branch name
      id: extract_branch
      run: echo "branch=${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

