FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

# Update the OS
RUN apt-get update && apt-get upgrade -y

# Install OS dependencies
RUN apt-get install -y curl gnupg wget git bash tree zsh

# Install node dependencies
RUN npm install -g pnpm
RUN pnpm dlx playwright install
RUN pnpm dlx playwright install-deps