FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

# Update the OS
RUN apt-get update && apt-get upgrade -y

# Install OS dependencies
RUN apt-get install -y curl gnupg wget git bash tree zsh

# Install node dependencies
RUN npm install -g pnpm
RUN pnpm dlx playwright install
RUN pnpm dlx playwright install-deps

# # ========= Users =========
# ARG IS_VSCODE=true
# RUN if [ "$IS_VSCODE" = "false" ]; then exit 0; fi

# # Setup VSCode user. This is to ensure you dont run into any file conflicts with the vscode mount and the container
# ARG USERNAME=vscode
# ARG USER_UID=1000
# ARG USER_GID=$USER_UID

# # Create the user
# RUN groupadd --gid $USER_GID $USERNAME \
#     && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
#     # Add sudo permissions
#     && apt-get update \
#     && apt-get install -y sudo \
#     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME

# # Create folder as root
# RUN mkdir /commandhistory 
# RUN touch /commandhistory/.bash_history 
# RUN chown -R $USERNAME /commandhistory 

# USER $USERNAME

# # Used to persist bash history as per https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
# RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" && echo "$SNIPPET" >> "/home/$USERNAME/.bashrc"

