name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  get_git_info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Git Info
        id: git_info
        uses: ./.github/actions/get-git-branch

  publish_server_build_image:
    needs: get_git_info
    runs-on: ubuntu-latest
    steps :
      - name: Publish serverbuild info
        uses: ./.github.actions/publish-build-image
        with: 
          docker-image-tag: aria-server-build-${{ needs.get_git_branch.outputs.branch }}
          docker-file-path: ./src/server/Dockerfile.build
  
  publish_client_build_image:
    needs: get_git_info
    runs-on: ubuntu-latest
    steps :
      - name: Publish build info
        uses: ./.github.actions/publish-build-image
        with: 
          docker-image-tag: aria-client-build-${{ needs.get_git_branch.outputs.branch }}
          docker-file-path: ./src/client/Dockerfile.build

  build_server_app:
    needs: [publish_server_build_image, get_git_info]
    if: always()
    runs-on: ubuntu-latest
    container:
      image: aria-server-build-${{ needs.get_git_branch.outputs.branch }}
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: bash ./src/server/build.sh         
  
  build_client_app:
    needs: [publish_client_build_image, get_git_info]
    if: always()
    runs-on: ubuntu-latest
    container:
      image: aria-client-build-${{ needs.get_git_branch.outputs.branch }}
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache items in the node modules folder, update cache if the packages lock file changes
      # This means that if the lock file does not change, then we will copy the cached node modules folder
      - name: Cache node modules
        id: node-module-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./src/client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
        working-directory: ./src/client

      - name: Build
        run: bash ./src/client/build.sh

